module.exports = [ { status: 2,
    desc: 'Down-sized systemic analyzer',
    is_checked: 0 },
  { status: 1, desc: 'Down-sized exuding project', is_checked: 0 },
  { status: 5,
    desc: 'Up-sized homogeneous benchmark',
    is_checked: 0 },
  { status: 1,
    desc: 'Business-focused discrete Graphical User Interface',
    is_checked: 0 },
  { status: 5, desc: 'Expanded mobile attitude', is_checked: 0 },
  { status: 3, desc: 'Profit-focused exuding core', is_checked: 0 },
  { status: 4,
    desc: 'Managed web-enabled extranet',
    is_checked: 0 },
  { status: 2,
    desc: 'Re-contextualized optimizing success',
    is_checked: 0 },
  { status: 3,
    desc: 'Organized heuristic artificial intelligence',
    is_checked: 0 },
  { status: 5,
    desc: 'Automated exuding time-frame',
    is_checked: 0 },
  { status: 2, desc: 'Reduced even-keeled website', is_checked: 0 },
  { status: 5,
    desc: 'Ergonomic bandwidth-monitored infrastructure',
    is_checked: 0 },
  { status: 4,
    desc: 'Down-sized 24 hour knowledge user',
    is_checked: 0 },
  { status: 1,
    desc: 'User-friendly transitional hierarchy',
    is_checked: 0 },
  { status: 2,
    desc: 'Digitized background encryption',
    is_checked: 0 },
  { status: 1,
    desc: 'Operative asymmetric application',
    is_checked: 0 },
  { status: 2,
    desc: 'Digitized dedicated open system',
    is_checked: 0 },
  { status: 4,
    desc: 'Upgradable methodical implementation',
    is_checked: 0 },
  { status: 3,
    desc: 'Organized homogeneous ability',
    is_checked: 0 },
  { status: 4, desc: 'Upgradable 24 hour firmware', is_checked: 0 },
  { status: 5, desc: 'Expanded scalable structure', is_checked: 0 },
  { status: 3,
    desc: 'Adaptive optimal implementation',
    is_checked: 0 },
  { status: 5, desc: 'Focused exuding project', is_checked: 0 },
  { status: 1,
    desc: 'Synchronised uniform analyzer',
    is_checked: 0 },
  { status: 3,
    desc: 'Self-enabling fault-tolerant local area network',
    is_checked: 0 },
  { status: 5,
    desc: 'Team-oriented stable knowledge base',
    is_checked: 0 },
  { status: 3,
    desc: 'Progressive encompassing methodology',
    is_checked: 0 },
  { status: 4,
    desc: 'Operative non-volatile support',
    is_checked: 0 },
  { status: 5,
    desc: 'Visionary stable focus group',
    is_checked: 0 },
  { status: 4, desc: 'Stand-alone 24/7 structure', is_checked: 0 },
  { status: 1,
    desc: 'Function-based 4th generation open architecture',
    is_checked: 0 },
  { status: 5, desc: 'Virtual global attitude', is_checked: 0 },
  { status: 1,
    desc: 'Operative asymmetric service-desk',
    is_checked: 0 },
  { status: 1,
    desc: 'Monitored heuristic task-force',
    is_checked: 0 },
  { status: 1,
    desc: 'Decentralized bi-directional protocol',
    is_checked: 0 },
  { status: 3,
    desc: 'Multi-layered web-enabled orchestration',
    is_checked: 0 },
  { status: 4,
    desc: 'Exclusive user-facing knowledge base',
    is_checked: 0 },
  { status: 4,
    desc: 'Profound tangible Graphical User Interface',
    is_checked: 0 },
  { status: 3, desc: 'Proactive hybrid hierarchy', is_checked: 0 },
  { status: 2,
    desc: 'Right-sized zero defect methodology',
    is_checked: 0 },
  { status: 4,
    desc: 'Horizontal multi-tasking workforce',
    is_checked: 0 },
  { status: 2,
    desc: 'Up-sized regional focus group',
    is_checked: 0 },
  { status: 3,
    desc: 'Secured mobile internet solution',
    is_checked: 0 },
  { status: 1,
    desc: 'Sharable contextually-based protocol',
    is_checked: 0 },
  { status: 5,
    desc: 'Fundamental mission-critical array',
    is_checked: 0 },
  { status: 1,
    desc: 'Self-enabling dynamic projection',
    is_checked: 0 },
  { status: 5,
    desc: 'Programmable directional paradigm',
    is_checked: 0 },
  { status: 3,
    desc: 'Monitored coherent utilisation',
    is_checked: 0 },
  { status: 2,
    desc: 'Assimilated systematic software',
    is_checked: 0 },
  { status: 2,
    desc: 'Persistent homogeneous secured line',
    is_checked: 0 },
  { status: 2,
    desc: 'De-engineered empowering website',
    is_checked: 0 },
  { status: 3,
    desc: 'Stand-alone attitude-oriented model',
    is_checked: 0 },
  { status: 2,
    desc: 'Fundamental content-based neural-net',
    is_checked: 0 },
  { status: 2,
    desc: 'Business-focused motivating initiative',
    is_checked: 0 },
  { status: 4,
    desc: 'Down-sized even-keeled protocol',
    is_checked: 0 },
  { status: 3,
    desc: 'Upgradable asynchronous definition',
    is_checked: 0 },
  { status: 3,
    desc: 'Right-sized encompassing leverage',
    is_checked: 0 },
  { status: 5,
    desc: 'Devolved asynchronous database',
    is_checked: 0 },
  { status: 5,
    desc: 'Customer-focused object-oriented hierarchy',
    is_checked: 0 },
  { status: 3, desc: 'Multi-layered 24/7 portal', is_checked: 0 },
  { status: 1,
    desc: 'Right-sized optimizing standardization',
    is_checked: 0 },
  { status: 4,
    desc: 'De-engineered multi-tasking alliance',
    is_checked: 0 },
  { status: 3,
    desc: 'Versatile tertiary collaboration',
    is_checked: 0 },
  { status: 5,
    desc: 'Streamlined mission-critical migration',
    is_checked: 0 },
  { status: 4, desc: 'Phased eco-centric array', is_checked: 0 },
  { status: 4,
    desc: 'Decentralized high-level hierarchy',
    is_checked: 0 },
  { status: 1,
    desc: 'Integrated intermediate application',
    is_checked: 0 },
  { status: 5,
    desc: 'Reactive explicit customer loyalty',
    is_checked: 0 },
  { status: 2,
    desc: 'Persistent regional complexity',
    is_checked: 0 },
  { status: 4,
    desc: 'Customizable object-oriented paradigm',
    is_checked: 0 },
  { status: 1,
    desc: 'Decentralized explicit synergy',
    is_checked: 0 },
  { status: 3,
    desc: 'Reactive zero administration emulation',
    is_checked: 0 },
  { status: 3,
    desc: 'Fully-configurable real-time interface',
    is_checked: 0 },
  { status: 2,
    desc: 'Reactive intermediate internet solution',
    is_checked: 0 },
  { status: 3,
    desc: 'Expanded asynchronous interface',
    is_checked: 0 },
  { status: 2, desc: 'Ergonomic systematic model', is_checked: 0 },
  { status: 2,
    desc: 'Robust grid-enabled capability',
    is_checked: 0 },
  { status: 1,
    desc: 'Public-key exuding moratorium',
    is_checked: 0 },
  { status: 4,
    desc: 'Diverse object-oriented task-force',
    is_checked: 0 },
  { status: 3,
    desc: 'Extended bifurcated utilisation',
    is_checked: 0 },
  { status: 2,
    desc: 'Profit-focused leading edge forecast',
    is_checked: 0 },
  { status: 1, desc: 'Seamless tangible algorithm', is_checked: 0 },
  { status: 2,
    desc: 'Object-based holistic archive',
    is_checked: 0 },
  { status: 5,
    desc: 'Up-sized mission-critical Graphic Interface',
    is_checked: 0 },
  { status: 2,
    desc: 'Implemented secondary leverage',
    is_checked: 0 },
  { status: 5,
    desc: 'Expanded clear-thinking migration',
    is_checked: 0 },
  { status: 5, desc: 'Visionary hybrid throughput', is_checked: 0 },
  { status: 5,
    desc: 'Proactive 3rd generation definition',
    is_checked: 0 },
  { status: 3,
    desc: 'Function-based hybrid protocol',
    is_checked: 0 },
  { status: 4,
    desc: 'Organized maximized migration',
    is_checked: 0 },
  { status: 4,
    desc: 'Assimilated grid-enabled open architecture',
    is_checked: 0 },
  { status: 2,
    desc: 'Monitored intangible solution',
    is_checked: 0 },
  { status: 3,
    desc: 'Proactive full-range service-desk',
    is_checked: 0 },
  { status: 5,
    desc: 'Devolved uniform info-mediaries',
    is_checked: 0 },
  { status: 2,
    desc: 'Ergonomic asynchronous portal',
    is_checked: 0 },
  { status: 5,
    desc: 'Robust actuating budgetary management',
    is_checked: 0 },
  { status: 5,
    desc: 'Grass-roots radical firmware',
    is_checked: 0 },
  { status: 4,
    desc: 'Extended demand-driven interface',
    is_checked: 0 },
  { status: 3,
    desc: 'Monitored 4th generation info-mediaries',
    is_checked: 0 },
  { status: 1,
    desc: 'Fully-configurable regional time-frame',
    is_checked: 0 } ];
